trigger:
  branches:
    include:
      - main

pool:
  name: Default  # Use your configured agent pool

steps:
# Step 1: Checkout Code
- checkout: self
  displayName: 'Checkout code from GitHub'

- script: |
    echo "Building the project..."
    mvn clean package
  displayName: 'Build and Test'

- script: |
    echo "Listing target directory..."
    ls -l target
  displayName: 'Debug Target Directory'

# Step 2: Debugging
- script: |
    echo "Testing minimal pipeline"
  displayName: 'Test Pipeline'
