trigger:
  branches:
    include:
      - main

pool:
  name: Default  # Use the pool where your self-hosted agent is configured

steps:
- script: |
    echo "Running pipeline on self-hosted agent!"
    mvn clean package
  displayName: 'Build and Test'
